### ISSUE TITLE
Only step 0 is shown in output

### ISSUE THREAD

**Issue by VadimKirilchuk** [vjuranek/docker-build-step-plugin#14]
Here is an output of my job:

```
+ cat Dockerfile
FROM spotify/cassandra
RUN apt-get update && apt-get -y install git
RUN git clone somerepo
+ cd -

/tmp/jenkins/workspace/Docker_Cassandra_Image
[Docker] INFO: Creating docker image from /tmp/jenkins/workspace/Docker_Cassandra_Image/Docker
Step 0 : FROM spotify/cassandra

[Docker] INFO: Sucessfully created image imagename
```

As you can see plugin outputs only "step 0", but there is nothing about further steps.

Here is an output of doing build manually with CLI:

```
$ docker build --rm=true .
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM spotify/cassandra
 ---> 34922801b8fd
Step 1 : RUN apt-get update && apt-get -y install git
 ---> Using cache
 ---> bc95b034410d
Step 2 : RUN git clone somerepo
 ---> Using cache
 ---> 0e7d445b42af
Successfully built 0e7d445b42af
```

Am I doing anything wrong?

**Comment by vjuranek** [comment]
Hi,
sorry for late reply. Is the issue still present? I just tried and all steps are shown. Maybe fixed by changes done in meantime.
Thanks

**Comment by vjuranek** [comment]
ops, closed by accident, reopening....

**Comment by VadimKirilchuk** [comment]
Hello,

Sorry. but I don't have the time to check right now. ETA 1 month, sorry) And thanks for reply.

**Comment by vjuranek** [comment]
no problem, let me know once you get to it ...

**Comment by VadimKirilchuk** [comment]
Sorry, no time to double check that, so closing.
