### ISSUE TITLE
Remove options on container started from images

### ISSUE THREAD

**Issue by dieend** [vjuranek/docker-build-step-plugin#18]
How does container started from images works? Is it possible to use `--rm` options?
something like:
```
docker run --rm images/name
```
https://docs.docker.com/reference/commandline/cli/#run

**Comment by vjuranek** [comment]
Hi,
plugin uses Docker REST API and if I'm not mistaken, this is currently provided neither by [Create container cmd](https://docs.docker.com/reference/api/docker_remote_api_v1.19/#create-a-container) not [start container cmd](https://docs.docker.com/reference/api/docker_remote_api_v1.19/#start-a-container). I.e. use `--rm` option is currently not possible.
