### ISSUE TITLE
Network bridge

### ISSUE THREAD

**Issue by ojacquemart** [vjuranek/docker-build-step-plugin#21]
Hello,

I have some issue to access to a container started by the plugin.
In fact, the container is launched. I can see it through the `docker ps` but I can't access my app deployed directly through my local ip. I must retrieve the ip by the `docker inspect` command (172.17...).

When I start the same container using the command line, I can access the app (http://127.0.0.1:8181).
By doing a diff between on the `docker inspect`, I can see that there the network bridge is not present from the container started using the docker-build-step-plugin.

Any idea on how to start the container with the plugin and access it with my local ip?

**Comment by vjuranek** [comment]
Hi,
you need to specifi port binding in `Advanced` options. Clink on `?` to check the syntax of the binding.
HTH, please reopen if you have any issues.
Thanks
