### ISSUE TITLE
Save Image command: No name specified

### ISSUE THREAD

**Issue by cviebig** [vjuranek/docker-build-step-plugin#22]
Hi,

how do I specify the image name in order to run the Save Image command in version 1.26? Unfortunately there are no input fields exposed to configure these settings. Did I miss them somewhere else?

Thank you very much in advance! :)

Best
Christoph

**Comment by cviebig** [comment]
To be honest, I'm a bit lost now. I would like to run `docker build` using the plugin. As this command is not directly available I expected to get a similiar behauvior by running `Create image` and `Save image` but this doesn't seem to be the case, right?

At least calling the command with the appropiate parameters does not give the result I want :) For this I had to add a new parameter template for SaveImage cmd (similiar too [CreateImageCommand/config-detail.jelly](https://github.com/vjuranek/docker-build-step-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateImageCommand/config-detail.jelly) for [CreateImageCommand.java](https://github.com/vjuranek/docker-build-step-plugin/blob/master/src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateImageCommand.java)). Is this missing in #19 ?

**Comment by vjuranek** [comment]
Hi,
what actually you want to achieve? IMHO `docker build` gives you the same as using `Create image` command. I'll add `/build` into the command name to make it more explicit, that these two intend to do the same thing.
Thanks

**Comment by cviebig** [comment]
Oh, I'm very sorry. I badly misinterpreted the tag field of the create command and consequently did not change it to my image name. Because of this I could not find the newly built image. Now it works. Thank you!
