### ISSUE TITLE
Building an image leaves the intermediate containers behind

### ISSUE THREAD

**Issue by kuon** [vjuranek/docker-build-step-plugin#3]
When using a create image build step, it leaves the intermediate containers behind.

Like this:

    d04f76fb87c6        4050983437f7  /bin/sh -c '#(nop) A   11 seconds ago   goofy_sammet            
    e81153e1089e        1cdbda7f82fe  /bin/sh -c '#(nop) C   11 seconds ago   sleepy_shockley         
    62d350f9a0f5        7d653bf196f1  /bin/sh -c '#(nop) A   12 seconds ago   berserk_turing          
    6a373c8972e8        ac180c8df803  /bin/sh -c '#(nop) A   12 seconds ago   jolly_kirch             
    e03188a5bd90        3379c3622194  /bin/sh -c '#(nop) A   13 seconds ago   trusting_kowalevski     
    4a7db4760427        46a9d58820c7  /bin/sh -c '#(nop) A   13 seconds ago   romantic_pare           
    0d6e7b499c92        52321abb4380  /bin/sh -c '#(nop) E   14 seconds ago   condescending_galileo   
    4549a5d97cdc        d92c5df81616  /bin/sh -c '#(nop) E   14 seconds ago   boring_poincare         
    3c9d57d63db7        7c2f2941feb9  /bin/sh -c '#(nop) E   14 seconds ago   hungry_colden

**Comment by VadimKirilchuk** [comment]
Could you please check if it is fixed in newer versions? Because I do see that at least in 1.22 there are no intermediate images left.

**Comment by vjuranek** [comment]
Should be fixed by 1516ee9a44259f1
