### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jontro** [vjuranek/docker-build-step-plugin#46]
Looks like there is a lot of nice fixes in the changelog. When will the next time this plugin is release?

**Comment by vjuranek** [comment]
I want to do the next release once I fix the documentation which is really horrible:-( I also want to look on `docker-java` upgrade to version 3 if there are any back incompatibilities, which I missed during PR review. I still haven't found time for it, so the plan is either to look on it over the Christmas or release the plugin as it is by beginning of the new year (for sure I'd add, that I mean 2017, not 2018 or later:-). 
Really sorry for that:-(

**Comment by jontro** [comment]
No problems, thanks for the great work!

**Comment by vjuranek** [comment]
I'd keep it open until the release as a decent reminder:-)

**Comment by vjuranek** [comment]
didn't forgot on this one - will release during this week (unfortunately without any significant doc update:-()

**Comment by vjuranek** [comment]
released as `1.37`
