### ISSUE TITLE
plugin version 1.38 Unsupported protocol scheme found

### ISSUE THREAD

**Issue by norricorp** [vjuranek/docker-build-step-plugin#48]
Hi Vojtech,
I am using docker 1.12.5 on my Jenkins server and get the message above. 
The latest version of the plugin is 1.35 from May. Will there be a new version of the plugin to fix this?
I had a quick look through the code and in CreateContainerCommand.java, there is the line
    HostConfig hc = new HostConfig();
but the hc variable does not seem to be used so I wonder if the line can be removed?
But having tried that it caused the plugin to fail far more quickly so a very bad idea!
Regards

**Comment by ed007m** [comment]
I have the same trouble

**Comment by norricorp** [comment]
is there a plan to fix this?

**Comment by norricorp** [comment]
open new issue with better diagnostics
