### ISSUE TITLE
building plugin from source fails unit tests

### ISSUE THREAD

**Issue by norricorp** [vjuranek/docker-build-step-plugin#50]
Hi,
not sure if I am doing the right thing but cloned repo and build on windows (mvn install).
Results :
Tests in error:
  FailedTest.org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite » IO Fai...
PluginAutomaticTestBuilder$CliSanityTest>HudsonTestCase.runBare:293->HudsonTestCase.tearDown:414 » IO
Tests run: 64, Failures: 0, Errors: 2, Skipped: 0

Both failures seem to be linked to 
org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite(org.jvnet.hudson.test.junit.FailedTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.io.IOException: Failed to clean up temp dirs.
Caused by: java.nio.file.FileSystemException: C:\Users\.....\AppData\Local\Temp\hudson8035348588457570422test\secret.key: The process cannot access the file because it is being used by another process.

Can someone explain what is going on here and can it be ignored?

**Comment by vjuranek** [comment]
Hi, it seems to be some issue on your environment (maybe related to windows), as test suite is passing on my local machine as well as on CloudBees Jenkins (see [test result trend](https://jenkins.ci.cloudbees.com/job/plugins/job/docker-build-step-plugin/)). Another possibility is that this is some race condition in the test suite. In both cases this shouldn't mean there's a bug in the plugin and thus can be ignored.
