### ISSUE TITLE
dockerCertPath needs to be a property

### ISSUE THREAD

**Issue by flybyray** [vjuranek/docker-build-step-plugin#55]
dockerCertPath is not a property. Thus the field "cert file path" is not restored after restarts and will be empty in jenkins configure view.
[cert file path](https://www.screencast.com/t/OabtpjVC6OU)

**Comment by flybyray** [comment]
#56

**Comment by vjuranek** [comment]
Done in 67d580e84fb64d076e43af9c79c3287865939bc7
